language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- chmod +x lobbuble/gradlew
- chmod +rx lobbuble/app
skip_cleanup: true
script:
- ./lobbuble/gradlew clean build